### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by wwwlicious** [NetCoreTemplates/vue-lite#1]
FYI, I'm seeing a startup error when running `dotnet watch run` after creating project with `x` version `0.0.29`
```
Startup.cs(67,17): error CS0117: 'SharpPagesFeature' does not contain a definition for 'EnableSpaFallback' [C:\dev\jolly-moose\jollymoose\jollymoose.csproj]
```

**Comment by wwwlicious** [comment]
Nevermind, it was a cached pre-release issue.

**Comment by mythz** [comment]
Yep, BTW the `vue-lite` and `react-lite` templates have been recently updated to use a similar project structure to the [SharpData .NET Core App](https://forums.servicestack.net/t/new-sharpdata-net-core-app/8560) where all the .js library references and bootstrap.css are sourced from ServiceStack.Desktop.dll which will simplify updates and deployment as only a single .dll needs to be updated to update all its library dependencies.
